on:
  push:
    tags:
      - v*.*.*

jobs:
  pushlish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Publish
        run: chmod +x ./gradlew && ./gradlew :plugin:publishPlugins -Pgradle.publish.version=$GRADLE_PUBLISH_VERSION -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
        env:
          GRADLE_PUBLISH_VERSION: ${{steps.get_version.outputs.VERSION}}
          GRADLE_PUBLISH_KEY: ${{secrets.GRADLE_PUBLISH_KEY}}
          GRADLE_PUBLISH_SECRET: ${{secrets.GRADLE_PUBLISH_SECRET}}
